version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image:  node:14.21
  entrypoint: ["node"]
  working_dir: /root
  restart: always
  volumes:
    - ./:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-env-defaults: &env
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  SENDGRID_API_KEY: ${SENDGRID_API_KEY-(unset)}
  SENDGRID_DEV_TO: ${SENDGRID_DEV_TO-support@parameter1.com}
  YARN_CACHE_FOLDER: /.yarn-cache
  IDENTITYX_API_TOKEN: ${IDENTITYX_API_TOKEN}
  IDENTITYX_GRAPHQL_URI: ${IDENTITYX_GRAPHQL_URI-https://identity-x.parameter1.com/graphql}
  RECAPTCHA_V3_SITE_KEY: ${RECAPTCHA_V3_SITE_KEY-}
  RECAPTCHA_V3_SECRET_KEY: ${RECAPTCHA_V3_SECRET_KEY-}

x-env-local-dev: &env-local-dev
  GRAPHQL_URI: ${GRAPHQL_URI-http://host.docker.internal:10103}
  OEMBED_URI: ${OEMBED_URI-https://host.docker.internal:10402}
  RSS_URI: ${RSS_URI-http://host.docker.internal:10203}
  SITEMAPS_URI: ${SITEMAPS_URI-http://host.docker.internal:10303}

x-env-leonis: &env-leonis
  GRAPHQL_URI: ${GRAPHQL_URI-https://graphql.leonis.base.parameter1.com}
  OEMBED_URI: ${OEMBED_URI-https://oembed.leonis.base.parameter1.com}
  RSS_URI: ${RSS_URI-https://rss.leonis.base.parameter1.com}
  SITEMAPS_URI: ${SITEMAPS_URI-https://sitemaps.leonis.base.parameter1.com}
  BASE_BROWSE_GRAPHQL_URI: ${BASE_BROWSE_GRAPHQL_URI-https://base-browse.leonis.base.parameter1.com/graphql}

x-env-virgon: &env-virgon
  GRAPHQL_URI: ${GRAPHQL_URI-https://graphql.virgon.base.parameter1.com}
  OEMBED_URI: ${OEMBED_URI-https://oembed.virgon.base.parameter1.com}
  RSS_URI: ${RSS_URI-https://rss.virgon.base.parameter1.com}
  SITEMAPS_URI: ${SITEMAPS_URI-https://sitemaps.virgon.base.parameter1.com}
  BASE_BROWSE_GRAPHQL_URI: ${BASE_BROWSE_GRAPHQL_URI-https://base-browse.virgon.base.parameter1.com/graphql}

x-site-command: &site-cmd
  <<: *node
  entrypoint: ["yarn"]
  command: ["dev"]

volumes:
  yarn-cache: {}

services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  in:
    <<: *site-cmd
    working_dir: /root/sites/investmentnews.com
    environment:
      <<: *env
      HOST: www-bonhill-in.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9971
      LIVERELOAD_PORT: 19971
    hostname: www-bonhill-in.dev.parameter1.com
    ports:
      - "9971:80"
      - "19971:19971"
