name: Integration Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build-and-test-image:
    uses: parameter1/actions/.github/workflows/website-build-push-test.yml@main
    strategy:
      matrix:
        ###############################################
        #v# Make sure this matches the site matrix! #v#
        ###############################################
        site:
          - { dir: investmentnews.com, stack: leonis, id: 635ac2b4da016482237f5d28, account: bonhill, tenant: bonhill_all, rancher_label: bonhill-group-investmentnews.com }
        ###############################################
        #^# Make sure this matches the site matrix! #^#
        ###############################################
    with:
      docker_image: website-${{ matrix.site.dir }}
      site_host: ${{ matrix.site.dir }}
      ecr_registry: ${{ vars.AWS_ECR_REGISTRY }}
